
export const TIME_CONSTANTS = {
  TOAST_DURATION: 3000,
  ANIMATION_DURATION: 1500,
  DEBOUNCE_DELAY: 300,
};

export const COLORS = {
  SUCCESS: '#34D399',
  ERROR: '#F87171',
  WARNING: '#FBBF24',
  INFO: '#60A5FA',
  PROFIT: '#34D399',
  LOSS: '#F87171',
  BALANCE: '#60A5FA',
};

export const DEFAULT_GOALS = {
  monthlyTarget: 1000000,
  weeklyTarget: 250000,
  targetWinRate: 70,
  yearlyTarget: 12000000,
};

export const FILTER_OPTIONS = {
  ALL: 'all',
  PROFIT: 'profit',
  LOSS: 'loss',
  THIS_WEEK: 'thisWeek',
  LARGE: 'large',
};

export const TABS = {
  DASHBOARD: 'dashboard',
  ANALYTICS: 'analytics',
  TRADES: 'trades',
  JOURNAL: 'journal',
};

export const ACTIONS = {
  SET_TRADES: 'SET_TRADES',
  ADD_TRADE: 'ADD_TRADE',
  UPDATE_TRADE: 'UPDATE_TRADE',
  DELETE_TRADE: 'DELETE_TRADE',
  SET_GOALS: 'SET_GOALS',
  SET_STRATEGIES: 'SET_STRATEGIES',
  ADD_STRATEGY: 'ADD_STRATEGY',
  UPDATE_STRATEGY: 'UPDATE_STRATEGY',
  DELETE_STRATEGY: 'DELETE_STRATEGY',
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  SET_SHOW_FORM: 'SET_SHOW_FORM',
  SET_SHOW_GOAL_MODAL: 'SET_SHOW_GOAL_MODAL',
  SET_SHOW_STRATEGIES_MODAL: 'SET_SHOW_STRATEGIES_MODAL',
  SET_SHOW_MEMO_MODAL: 'SET_SHOW_MEMO_MODAL',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_EDITING_TRADE: 'SET_EDITING_TRADE',
  SET_CURRENT_TRADE: 'SET_CURRENT_TRADE',
  SET_EDITING_STRATEGY: 'SET_EDITING_STRATEGY',
  SET_CURRENT_STRATEGY: 'SET_CURRENT_STRATEGY',
  RESET_EDITING: 'RESET_EDITING',
  SET_CURRENT_MEMO: 'SET_CURRENT_MEMO',
  SET_SELECTED_DATE: 'SET_SELECTED_DATE',
  SET_JOURNAL_ENTRIES: 'SET_JOURNAL_ENTRIES',
  ADD_JOURNAL_ENTRY: 'ADD_JOURNAL_ENTRY',
  UPDATE_JOURNAL_ENTRY: 'UPDATE_JOURNAL_ENTRY',
  DELETE_JOURNAL_ENTRY: 'DELETE_JOURNAL_ENTRY',
  SET_CURRENT_JOURNAL_ENTRY: 'SET_CURRENT_JOURNAL_ENTRY',
  SET_SELECTED_JOURNAL_DATE: 'SET_SELECTED_JOURNAL_DATE',
};
